spring.jms.servicebus.connection-string: <ServiceBusNamespaceConnectionString>
spring.jms.servicebus.topic-client-id: <ServiceBusSubscriptionID>
spring.jms.servicebus.idle-timeout: <IdleTimeout>
spring.jms.servicebus.pricing-tier: <ServiceBusPricingTier> 