spring.jms.servicebus.connection-string: <spring.jms.servicebus.connection-string>
spring.jms.servicebus.topic-client-id: <spring.jms.servicebus.topic-client-id>
spring.jms.servicebus.pricing-tier: <standard/premium/basic>

server.port: 7070

